category = {
    "Dresses": {
        "age": {"adult", "children"},
        "gender": {"women"},
        "Closure": {"Full closure", "No closure", "Partial closure"},
        "Fastening": {"Fastening", "No fastening"},
        "Fastening type": {
            "buckle",
            "buttons",
            "drawstrings",
            "toggles",
            "wrap & knot",
            "zipper",
        },
        "Skirt": {
            "a-line",
            "balloon",
            "mermaid",
            "pencil and straight",
            "pleated",
            "tiered",
            "tutu",
            "wrap skirts",
        },
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Cut": {"shorted", "shoulder straps", "spaghetti straps", "strapless"},
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Length": {"maxi", "midi", "mini", "not visible"},
        "Neckline": {
            "back",
            "boatneck",
            "bow",
            "collar",
            "cowl",
            "crew",
            "hooded",
            "low cut",
            "off shoulder",
            "one shoulder",
            "round",
            "square",
            "turtleneck",
            "v-neck",
            "wrap",
        },
        "Belt": {"Belt", "No belt"},
        "Material": {
            "corduroy",
            "cotton",
            "denim",
            "knitwear",
            "lace",
            "leather",
            "linen",
            "mesh/transparent",
            "silk",
            "suede",
            "tweed",
            "velvet",
        },
        "Style": {"casual", "cocktail dress", "evening dress", "sport",
                  "wedding"},
        "subcategory": {
            "blazer dresses",
            "blouse dresses",
            "bodycon dress",
            "casual dresses",
            "fit & flare dresses",
            "knitted dresses",
            "sheath dresses",
            "slip dress",
            "wrap dress",
        },
        "Layers": {"1st layer", "2nd layer"},
        "lining": {"Double-breasted", "Single-breasted"},
    },
    "Jackets and Coats": {
        "age": {"adult", "children"},
        "gender": {"men", "unisex", "women"},
        "Closure": {"Full closure", "No closure", "Partial closure"},
        "Fastening": {"Fastening", "No fastening"},
        "Fastening type": {
            "buckle",
            "buttons",
            "drawstrings",
            "toggles",
            "wrap & knot",
            "zipper",
        },
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Length": {"maxi", "midi", "mini", "not visible"},
        "Belt": {"Belt", "No belt"},
        "Material": {
            "denim",
            "fur",
            "leather & suede",
            "softshell",
            "synthetic",
            "textile",
            "tweed",
            "wool",
        },
        "Style": {"casual", "elegant", "sport"},
        "subcategory": {
            "baseball jacket",
            "biker jacket",
            "bomber jacket",
            "casual jackets",
            "duffle coat",
            "harrington jacket",
            "kimono coat",
            "knitted ponchos",
            "parka coat",
            "peacoat",
            "pilot jacket",
            "puffer jackets",
            "racer jacket",
            "raincoats and ponchos",
            "sportswear shorts",
            "suit jackets and tuxedos",
            "trench coats",
            "windstoppers & softshells",
            "winter coats",
            "winter jackets",
            "wool coats",
        },
        "hood": {"hood", "no hood", "not visible"},
        "Layers": {"1st layer", "2nd layer"},
        "lining": {"Double-breasted", "Single-breasted"},
    },
    "Nightwear Subcat.: nightdresses and negligees": {
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Cut": {"shorted", "shoulder straps", "spaghetti straps", "strapless"},
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Length": {"maxi", "midi", "mini", "not visible"},
        "Material": {
            "corduroy",
            "cotton",
            "denim",
            "knitwear",
            "lace",
            "leather",
            "linen",
            "mesh/transparent",
            "silk",
            "suede",
            "tweed",
            "velvet",
        },
        "hood": {"hood", "no hood", "not visible"},
        "sleeves": {
            "3/4 sleeves",
            "long sleeves",
            "one sleeve",
            "short sleeves",
            "sleeveless",
        },
    },
    "Nightwear Subcat.: pyjamas": {
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Length": {"3/4", "7/8", "Not visible pants", "long", "shorts"},
        "Material": {
            "corduroy",
            "cotton",
            "denim",
            "knitwear",
            "lace",
            "leather",
            "linen",
            "mesh/transparent",
            "silk",
            "suede",
            "tweed",
            "velvet",
        },
        "sleeves": {
            "3/4 sleeves",
            "long sleeves",
            "one sleeve",
            "short sleeves",
            "sleeveless",
        },
    },
    "Overalls and Dungarees": {
        "age": {"adult", "children"},
        "gender": {"men", "unisex", "women"},
        "Closure": {"Full closure", "No closure", "Partial closure"},
        "Fastening": {"Fastening", "No fastening"},
        "Fastening type": {
            "buckle",
            "buttons",
            "drawstrings",
            "toggles",
            "wrap & knot",
            "zipper",
        },
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Cut": {"shorted", "shoulder straps", "spaghetti straps", "strapless"},
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Neckline": {
            "back",
            "boatneck",
            "bow",
            "collar",
            "cowl",
            "crew",
            "hooded",
            "low cut",
            "off shoulder",
            "one shoulder",
            "round",
            "square",
            "turtleneck",
            "v-neck",
            "wrap",
        },
        "Belt": {"Belt", "No belt"},
        "Material": {
            "corduroy",
            "cotton",
            "denim",
            "knitwear",
            "lace",
            "leather",
            "linen",
            "mesh/transparent",
            "silk",
            "suede",
            "tweed",
            "velvet",
        },
        "subcategory": {
            "casual overalls",
            "elegant overalls",
            "winter overalls",
            "work overalls",
        },
        "hood": {"hood", "no hood", "not visible"},
        "Layers": {"1st layer", "2nd layer"},
        "lining": {"Double-breasted", "Single-breasted"},
        "sleeves": {
            "3/4 sleeves",
            "long sleeves",
            "one sleeve",
            "short sleeves",
            "sleeveless",
        },
        "fit": {"flared", "harem", "skinny", "slim", "straight", "wide leg"},
    },
    "Pants": {
        "age": {"adult", "children"},
        "gender": {"men", "unisex", "women"},
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Length": {"3/4", "7/8", "Not visible pants", "long", "shorts"},
        "Style": {"casual", "elegant", "sport"},
        "subcategory": {
            "beach pants",
            "cargo",
            "casual leggings",
            "casual shorts",
            "casual trousers ",
            "culottes",
            "denim shorts",
            "formal trousers",
            "hotpants",
            "jeans",
            "leather leggings",
            "leather shorts",
            "leather trousers",
            "leggings",
            "sportswear leggings",
            "sportswear shorts",
            "suit trousers",
            "sweat pants",
            "swim shorts",
        },
        "fit": {"flared", "harem", "skinny", "slim", "straight", "wide leg"},
        "rise": {"Can't tell", "High rise", "Low rise", "Mid rise"},
    },
    "Skirts": {
        "gender": {"women"},
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Cut": {"shorted", "shoulder straps", "spaghetti straps", "strapless"},
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Length": {"maxi", "midi", "mini"},
        "Material": {
            "corduroy",
            "cotton",
            "denim",
            "knitwear",
            "lace",
            "leather",
            "linen",
            "mesh/transparent",
            "silk",
            "suede",
            "tweed",
            "velvet",
        },
        "Style": {"casual", "elegant", "sport"},
        "subcategory": {
            "a-line",
            "balloon",
            "beach skirts",
            "casual skirts",
            "denim skirts",
            "formal skirts",
            "leather skirts",
            "mermaid",
            "pencil and straight",
            "pleated",
            "sportswear skirts",
            "tiered",
            "tutu ",
            "wrap skirts",
        },
        "rise": {"Can't tell", "High rise", "Low rise", "Mid rise"},
    },
    "Upper": {
        "age": {"adult", "children"},
        "gender": {"men", "unisex", "women"},
        "Closure": {"Full closure", "No closure", "Partial closure"},
        "Fastening": {"Fastening", "No fastening"},
        "Fastening type": {
            "buckle",
            "buttons",
            "drawstrings",
            "toggles",
            "wrap & knot",
            "zipper",
        },
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "Cut": {"shorted", "shoulder straps", "spaghetti straps", "strapless"},
        "Design": {
            "lace",
            "logo",
            "melange",
            "patterned",
            "picture",
            "plain",
            "shiny",
            "text",
        },
        "Pattern": {
            "animalistic",
            "camouflage",
            "checked",
            "chevron",
            "floral",
            "geometric & abstract",
            "polka dot",
            "stripe",
            "other",
        },
        "Neckline": {
            "back",
            "boatneck",
            "bow",
            "collar",
            "cowl",
            "crew",
            "hooded",
            "low cut",
            "off shoulder",
            "one shoulder",
            "round",
            "square",
            "turtleneck",
            "v-neck",
            "wrap",
        },
        "Belt": {"Belt", "No belt"},
        "Material": {
            "corduroy",
            "cotton",
            "denim",
            "knitwear",
            "lace",
            "leather",
            "linen",
            "mesh/transparent",
            "silk",
            "suede",
            "tweed",
            "velvet",
        },
        "Style": {"casual", "elegant", "sport", "smart casual"},
        "subcategory": {
            "bardot tops",
            "blouses",
            "cardigans",
            "crop tops",
            "cropped blouse",
            "denim shirt",
            "hoodies",
            "knitted tops",
            "knitted vests",
            "polo-shirts",
            "shell tops",
            "shirts",
            "sweaters",
            "sweatshirts",
            "t-shirts",
            "tank tops",
            "tops",
            "transparent tops",
            "tunics",
            "vests",
            "wrap tops",
        },
        "hood": {"hood", "no hood", "not visible"},
        "Layers": {"1st layer", "2nd layer"},
        "lining": {"Double-breasted", "Single-breasted"},
        "sleeves": {
            "3/4 sleeves",
            "long sleeves",
            "one sleeve",
            "short sleeves",
            "sleeveless",
        },
    },
    "Underwear/Tights": {
        "Color": {
            "beige",
            "black",
            "brown",
            "dark blue and navy",
            "golden",
            "green",
            "grey",
            "light blue",
            "orange",
            "pink",
            "purple and violet",
            "red",
            "silver",
            "turquoise",
            "white",
            "yellow",
            "multicolor",
        },
        "subcategory": {"stockings", "tights"},
    },
}
