TOP_WEAR = [
    "bardot tops",
    "blouses",
    "crop tops",
    "denim shirt",
    "hoodies",
    "sweaters",
    "polo-shirts",
    "shirts",
    "shell tops",
    "t-shirts",
    "tank tops",
    "transparent tops",
    "tunics",
    "wrap tops",
    "cropped blouse",
    "knitted tops",
    "tops",
    "sweatshirts"
]


BOTTOM_WEAR = [
    "beach pants",
    "cargo",
    "casual leggings",
    "casual shorts",
    "casual trousers",
    "culottes",
    "denim shorts",
    "formal trousers",
    "hotpants",
    "leather leggings",
    "leather shorts",
    "leather trousers",
    "sportswear leggings",
    "jeans:flared",
    "jeans:skinny",
    "jeans:slim",
    "jeans:straight",
    "jeans:wide leg",
    "jeans:harem",
    "sportswear shorts",
    "a-line",
    "balloon",
    "beach skirts",
    "denim skirts",
    "leather skirts",
    "mermaid skirts",
    "pleated",
    "tiered",
    "wrap skirts",
    "formal skirts",
    "leggings",
    "suit trousers",
    "casual skirts",
    "pencil and straight",
    "sweat pants",
]

western_N = len(TOP_WEAR)
western_M = len(BOTTOM_WEAR)

TRIANGLE = {"TOP_WEAR":  {14: 18,
                          11: 17,
                          2: 16,
                          1: 15,
                          16: 14,
                          0: 13,
                          15: 12,
                          9: 11,
                          10: 10,
                          7: 9,
                          5: 8,
                          17: 7,
                          3: 6,
                          4: 5,
                          12: 4,
                          13: 3,
                          8: 2,
                          6: 1},
            "BOTTOM_WEAR": {17: 35,
                            16: 34,
                            13: 33,
                            15: 32,
                            33: 31,
                            3: 30,
                            6: 29,
                            1: 28,
                            5: 27,
                            14: 26,
                            20: 25,
                            32: 24,
                            23: 23,
                            4: 22,
                            2: 21,
                            30: 20,
                            9: 19,
                            11: 18,
                            29: 17,
                            34: 16,
                            7: 15,
                            31: 14,
                            24: 13,
                            10: 12,
                            12: 11,
                            19: 10,
                            26: 9,
                            18: 8}}

INVERTED_TRIANGLE = {"TOP_WEAR":
                     {8: 18,
                      15: 17,
                      1: 16,
                      9: 15,
                      14: 14,
                      4: 13,
                      11: 12,
                      3: 11,
                      7: 10,
                      5: 9,
                      17: 8,
                      2: 7,
                      13: 6,
                      16: 5,
                      0: 4,
                      10: 3,
                      12: 2,
                      6: 1},
                     "BOTTOM_WEAR": {17: 35,
                                     13: 34,
                                     16: 33,
                                     6: 32,
                                     29: 31,
                                     11: 30,
                                     4: 29,
                                     15: 28,
                                     32: 27,
                                     1: 26,
                                     5: 25,
                                     20: 24,
                                     26: 23,
                                     2: 22,
                                     30: 21,
                                     9: 20,
                                     34: 19,
                                     33: 18,
                                     14: 17,
                                     7: 16,
                                     31: 15,
                                     23: 14,
                                     24: 13,
                                     3: 12,
                                     12: 11,
                                     19: 10,
                                     18: 9}}


ROUNDED = {"TOP_WEAR": {1: 18, 9: 17, 7: 16, 5: 15, 17: 14, 15: 13, 4: 12, 12: 11, 16: 10, 10: 9},
           "BOTTOM_WEAR": {17: 35,
                           16: 34,
                           13: 33,
                           5: 32,
                           32: 31,
                           4: 30,
                           1: 29,
                           29: 28,
                           7: 27,
                           31: 26,
                           11: 25,
                           34: 24,
                           23: 20,
                           26: 22,
                           3: 21,
                           12: 19}}

HOURGLASS = {"TOP_WEAR":
             {14: 18,
              2: 17,
              11: 16,
              15: 15,
              1: 14,
              0: 13,
              9: 12,
              16: 11,
              8: 10,
              10: 9,
              7: 8,
              3: 7,
              5: 6,
              17: 5,
              13: 4,
              4: 3,
              12: 2,
              6: 1},
             "BOTTOM_WEAR": {17: 35,
                             16: 34,
                             13: 33,
                             3: 32,
                             6: 31,
                             33: 30,
                             29: 29,
                             14: 28,
                             15: 27,
                             5: 26,
                             32: 25,
                             7: 24,
                             31: 23,
                             20: 22,
                             34: 21,
                             2: 20,
                             30: 19,
                             9: 18,
                             23: 17,
                             4: 16,
                             11: 15,
                             1: 14,
                             26: 13,
                             12: 12,
                             19: 11,
                             24: 10,
                             18: 9}}

RECTANGLE = {"TOP_WEAR": {2: 18, 15: 17, 16: 16, 11: 15, 14: 14, 0: 13,
                          10: 12, 9: 11, 4: 10, 3: 9, 7: 8, 5: 7,
                          17: 6, 1: 5, 8: 4, 13: 3, 12: 2, 6: 1},
             "BOTTOM_WEAR": {17: 35,
                             16: 34,
                             13: 33,
                             3: 32,
                             6: 31,
                             14: 30,
                             23: 29,
                             32: 28,
                             7: 27,
                             31: 26,
                             2: 25,
                             30: 24,
                             9: 23,
                             24: 22,
                             11: 21,
                             20: 20,
                             1: 19,
                             5: 18,
                             4: 17,
                             33: 16,
                             29: 15,
                             26: 14,
                             12: 13,
                             19: 12,
                             15: 11,
                             28: 10,
                             10: 9,
                             34: 4,
                             27: 7,
                             22: 6,
                             21: 5,
                             8: 3,
                             25: 2,
                             0: 1}}
                             
occasions = ["Keep It Casual", "Just Brunchin\'", "Work", "Date Night", "Party"]

WOMEN_WEST_PREFERENCS = {
    "AA000": {
        "Color": ["Black", "White", "Red", "Blue", "Green", "Yellow"],
        "Top": [21, 3, 7, 9],
        "Bottom": [27, 6, 3, 18],
        "Combination": [[0, 3], [1, 2], [2, 1], [3, 0]]
    },
    "VA109": {
        "Color": ["Black", "White", "Red", "Blue", "Green", "Yellow", "Pink"],
        "Top": [21, 3, 7, 9],
        "Bottom": [27, 6, 3, 18],
        "Combination": [[0, 3], [1, 2], [2, 1], [3, 0]]
    }
}